### PR TITLE
Fix diSPIM tiff reading

### PR DESCRIPTION
**Pull request by carshadi**
There is a performance issue with reading diSPIM tiffs using `tifffile`. Operations such as reading the number of planes and getting a random slice require seeking the entire (100+GB) file since `tifffile` does not know how to read ScanImage metadata. See this [gist](https://gist.github.com/carshadi/bce89fa047fe07d1274273edf8156dfa) for details.

This PR changes the tiff reading to use ScanImageTiffReader https://gitlab.com/vidriotech/scanimagetiffreader-python , which resolves the issue. 

It would probably be useful to use the `tifffile`-based reader for mesoSPIM datasets, since it is ~3-4X faster, but I didn't add that in this PR since we will likely not process any more mesoSPIM datasets in the near future.

### CODE REVIEW

**Comment by carshadi** [comment]
@jtyoung84 any idea on the build issue? I didn't see that when building locally...

**Comment by cgohlke** [comment]
> Operations such as reading the number of planes and getting a random slice require seeking the entire (100+GB) file since tifffile does not know how to read ScanImage metadata. 

Tifffile does attempt to read ScanImage metadata. There's a [function to read non-varying frame metadata](https://github.com/cgohlke/tifffile/blob/0c380b1ff86b084c0da79587cd99abc0301ab320/tifffile/tifffile.py#L19329-L19370), a [function to parse Matlab eval strings](https://github.com/cgohlke/tifffile/blob/0c380b1ff86b084c0da79587cd99abc0301ab320/tifffile/tifffile.py#L21811-L21975), a [method to speed up and/or fix reading corrupted ScanImage files](https://github.com/cgohlke/tifffile/blob/0c380b1ff86b084c0da79587cd99abc0301ab320/tifffile/tifffile.py#L6925-L6978), and a [method to parse the metadata into page series](https://github.com/cgohlke/tifffile/blob/0c380b1ff86b084c0da79587cd99abc0301ab320/tifffile/tifffile.py#L4747-L4802). 

The issue is that the new BigTIFF based ScanImage format no longer allows to calculate the number of frames and frame data offsets without parsing the TIFF IFD chain. It would be nice to known how the closed-source ScanImageTiffReader works around that, or if it is "just" the speed difference between a pure Python and a C implementation. 

83 s is really slow for parsing the IFD structure. Is the file on a network drive? In that case, using a locally produced [fsspec/kercunk](https://github.com/fsspec/kerchunk) reference file for the ScanImage file might be a better solution.

ScanImageTiffReader is very fast at reading image data from ScanImage files. It uses multiple-threads and OS specific file APIs, not the C stdlib (at least on Windows)...

**Comment by jtyoung84** [comment]
> @jtyoung84 any idea on the build issue? I didn't see that when building locally...

@carshadi I'm also able to build it locally. It's complaining about missing the wheel package. You can try to add it in the dependency list for the imaging libraries and see if that works.

**Comment by carshadi** [comment]
Hi @cgohlke , I appreciate your help!

> Tifffile does attempt to read ScanImage metadata.

 thanks for pointing that out, I had missed it

> Is the file on a network drive?

Yes, I am reading it from a NFS share connected to a fast flash storage server over a 40G network. I tried using `kerchunk` as you suggest and got a ~8X performance boost relative to the previous approach. 

```python
refs = tiff_to_zarr("path/to/scanimage.tiff")
refs_file = os.path.join(os.getcwd(), "references.json")
with open(refs_file, 'wb') as f:
    f.write(ujson.dumps(refs).encode())
fs = fsspec.filesystem(
    "reference", fo=refs_file, remote_protocol='file'
)
m = fs.get_mapper("")
ds = zarr.open(m, 'r')
print(ds)

ts = []
for i in range(0, ds.shape[0]):
    t0 = time.time()
    _ = ds[i]
    ts.append(time.time() - t0)

print(f"min: {min(ts)}")
print(f"max: {max(ts)}")
print(f"mean: {sum(ts) / len(ts)}")
```
output:
```
<zarr.core.Array (14200, 2304, 2304) uint16 read-only>
min: 0.0074117183685302734
max: 0.27079129219055176
mean: 0.022146293243891755
```

**Comment by carshadi** [comment]
@jtyoung84 tests are finally passing

**Review by jtyoung84 — APPROVED** [review]

**Pull request merged**
