### PR TITLE
feat: adds optional metadata folder upload

### LINKED ISSUE #172: Add capability to upload MRI data
# User story
As a user, I want to upload mri data to s3 and code ocean, so I can analyze the data in the cloud.

# Acceptance criteria
- [ ] There should be an option to upload mri data as part of the aind-data-transfer library
- [ ] The generic upload should suffice. Will need to add a option to point to a directory where metadata files are stored.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
Original comment:

We collect 4-8 MRI volumes a month, and have been uploading them to isilon for lack of a better backup and storage alternative. These data are as important as any other modality, and I would like the ability to put them S3 and work with them on codeocean.

### PR DESCRIPTION
**Pull request by jtyoung84**
Closes #172

- Adds option in s3_upload_job to point to a metadata folder.
- All json files found in folder will be uploaded to root path in s3://bucket/prefix
- No validation is performed.
- A few files such as subject.json inside the s3://bucket/prefix folder will be overwritten by the subject.json file built from aind-metadata-service
- This doesn't work with the ephys pipeline just yet. I'll open a new ticket to refactor the codebase to allow the ephys job to run using the same s3_upload_job method.

### CODE REVIEW

**Review by dyf — CHANGES_REQUESTED** [review]
If someone defines a metadata file that we have access to via aind-metadata-service, I think they should have to explicitly acknowledge that theirs is the right answer. Perhaps via an additional command line arg?

**Comment by jtyoung84** [comment]
> If someone defines a metadata file that we have access to via aind-metadata-service, I think they should have to explicitly acknowledge that theirs is the right answer. Perhaps via an additional command line arg?

I think if they point to a metadata folder, then we can assume that's the data the want to be the source of truth? @galenlynch Do you have an opinion on this?

**Comment by galenlynch** [comment]
Seems right, though maybe it could check for inconsistencies and require `-f` or something to indicate that the user really does know better?

**Comment by galenlynch** [comment]
Basically I agree with @dyf

**Review by dyf — APPROVED** [review]

**Pull request merged**
