### PR TITLE
Test xml metadata

### PR DESCRIPTION
**Pull request by cbrrrry**
Added test to evaluate xml metadata creation for stitching.

### CODE REVIEW

**Review by jtyoung84 — CHANGES_REQUESTED** [review]
We should try to mock the outputs of the function that parses the log contents instead of checking in a 600,000 line file

**Comment by mekhlakapoor** [comment]
@cbrrrry @jtyoung84 Is this still being worked on?

**Comment by cbrrrry** [comment]
No I think this is a stale branch now. We are no longer parsing these large log files, and thus mocking them is unnecessary. I will close this PR.

**Comment by mekhlakapoor** [comment]
Can we delete the branch

> No I think this is a stale branch now. We are no longer parsing these large log files, and thus mocking them is unnecessary. I will close this PR.

Can the branch be deleted?

**Comment by cbrrrry** [comment]
I think so. The relevant changes are being worked on in other branches/refactoring efforts.

**Pull request closed without merging**
